import 'dart:io';

import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:printing/printing.dart';

import '../domain/payroll_model.dart';
import 'payroll_service.dart';

class ExcelExportService {

static Future<void> exportPayroll(
PayrollModel employee,
int month,
int year,
) async {

final excel = Excel.createExcel();

final Sheet sheet =
excel['Payroll'];

final daysInMonth =
DateTime(
year,
month + 1,
0,
).day;

final perDaySalary =
employee.monthlySalary /
daysInMonth;

//--------------------------------------------------
// TITLE
//--------------------------------------------------

sheet.appendRow([
TextCellValue(
"STALLION ONE HRMS",
),
]);

sheet.appendRow([
TextCellValue(
"Employee Payroll Report",
),
]);

sheet.appendRow([]);

//--------------------------------------------------
// EMPLOYEE INFORMATION
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Employee Name"),
TextCellValue(employee.employeeName),
]);

sheet.appendRow([
TextCellValue("Employee ID"),
TextCellValue(employee.employeeId),
]);

sheet.appendRow([
TextCellValue("Role"),
TextCellValue(employee.role),
]);

sheet.appendRow([
TextCellValue("Month"),
TextCellValue("$month / $year"),
]);

sheet.appendRow([]);

//--------------------------------------------------
// SALARY DETAILS
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Monthly Salary"),
DoubleCellValue(employee.monthlySalary),
]);

sheet.appendRow([
TextCellValue("Per Day Salary"),
DoubleCellValue(perDaySalary),
]);

sheet.appendRow([
TextCellValue("Present Days"),
IntCellValue(employee.presentDays),
]);

sheet.appendRow([
TextCellValue("Half Days"),
IntCellValue(employee.halfDays),
]);

sheet.appendRow([
TextCellValue("Absent Days"),
IntCellValue(employee.absentDays),
]);

sheet.appendRow([]);

//--------------------------------------------------
// FINAL SALARY
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Calculated Salary"),
DoubleCellValue(
employee.calculatedSalary,
),
]);

sheet.appendRow([]);

//--------------------------------------------------
// GENERATED INFORMATION
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Generated Date"),
TextCellValue(
"${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
),
]);

sheet.appendRow([
TextCellValue(
"Generated By",
),
TextCellValue(
"Stallion One HRMS",
),
]);

sheet.appendRow([]);

sheet.appendRow([
TextCellValue(
"This report is automatically generated.",
),
]);    //--------------------------------------------------
// EMPLOYEE INFORMATION
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Employee Name"),
TextCellValue(employee.employeeName),
]);

sheet.appendRow([
TextCellValue("Employee ID"),
TextCellValue(employee.employeeId),
]);

sheet.appendRow([
TextCellValue("Role"),
TextCellValue(employee.role),
]);

sheet.appendRow([
TextCellValue("Month"),
TextCellValue("$month / $year"),
]);

sheet.appendRow([]);

//--------------------------------------------------
// SALARY DETAILS
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Monthly Salary"),
DoubleCellValue(employee.monthlySalary),
]);

sheet.appendRow([
TextCellValue("Per Day Salary"),
DoubleCellValue(perDaySalary),
]);

sheet.appendRow([
TextCellValue("Present Days"),
IntCellValue(employee.presentDays),
]);

sheet.appendRow([
TextCellValue("Half Days"),
IntCellValue(employee.halfDays),
]);

sheet.appendRow([
TextCellValue("Absent Days"),
IntCellValue(employee.absentDays),
]);

sheet.appendRow([]);

//--------------------------------------------------
// FINAL SALARY
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Calculated Salary"),
DoubleCellValue(
employee.calculatedSalary,
),
]);

sheet.appendRow([]);

//--------------------------------------------------
// GENERATED INFORMATION
//--------------------------------------------------

sheet.appendRow([
TextCellValue("Generated Date"),
TextCellValue(
"${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}",
),
]);

sheet.appendRow([
TextCellValue(
"Generated By",
),
TextCellValue(
"Stallion One HRMS",
),
]);

sheet.appendRow([]);

sheet.appendRow([
TextCellValue(
"This report is automatically generated.",
),
]);

  //--------------------------------------------------
  // SAVE EXCEL FILE
  //--------------------------------------------------

  final directory =
  await getApplicationDocumentsDirectory();

  final file = File(
    "${directory.path}/Payroll_${employee.employeeName}_${month}_$year.xlsx",
  );

  final bytes = excel.encode();

  if (bytes != null) {
    await file.writeAsBytes(bytes);
  }

  // File saved successfully.
  // You can later open or share this file if needed.
}
}