// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAS-FnJJ11jJI_gJeCsTbT6K63oIZNUvk',
    appId: '1:182550207384:web:0cd10e35065015c07369ed',
    messagingSenderId: '182550207384',
    projectId: 'stallion-one',
    authDomain: 'stallion-one.firebaseapp.com',
    storageBucket: 'stallion-one.firebasestorage.app',
    measurementId: 'G-X895QJECQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4a8eDO6yiTMafhjn830_fa6zS3ayCAEE',
    appId: '1:182550207384:android:4c321d30e8464f2a7369ed',
    messagingSenderId: '182550207384',
    projectId: 'stallion-one',
    storageBucket: 'stallion-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZ_3IrYTTECat7WVB8bLgzPnbHP4J4Bk',
    appId: '1:182550207384:ios:aefdead5e5d42ca47369ed',
    messagingSenderId: '182550207384',
    projectId: 'stallion-one',
    storageBucket: 'stallion-one.firebasestorage.app',
    iosBundleId: 'com.example.stallionOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZ_3IrYTTECat7WVB8bLgzPnbHP4J4Bk',
    appId: '1:182550207384:ios:aefdead5e5d42ca47369ed',
    messagingSenderId: '182550207384',
    projectId: 'stallion-one',
    storageBucket: 'stallion-one.firebasestorage.app',
    iosBundleId: 'com.example.stallionOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAS-FnJJ11jJI_gJeCsTbT6K63oIZNUvk',
    appId: '1:182550207384:web:6d6d83d89a8a646f7369ed',
    messagingSenderId: '182550207384',
    projectId: 'stallion-one',
    authDomain: 'stallion-one.firebaseapp.com',
    storageBucket: 'stallion-one.firebasestorage.app',
    measurementId: 'G-PJQ5GMWG6W',
  );
}
